In [3]:
import pandas as pd
Tdesempeno=pd.read_csv("Resultados_de_la_Medici_n_del_Desempe_o_Institucional (1).csv", sep=",",encoding="utf-8")
type(Tdesempeno)

pandas.core.frame.DataFrame

In [4]:
Tdesempeno

,CODIGO_SIGEP,ENTIDAD,NATURALEZA_JURIDICA,ORDEN,SECTOR,ID_MUNICIPIO,MUNICIPIO,GRUPOPAR,ID_INDICE,INDICE,PUNTAJE_ENTIDAD,VIGENCIA,PROMEDIO_GRUPO_PAR,MAXIMO_GRUPO_PAR,MINIMO_GRUPO_PAR,QUINTIL_GRUPO_PAR,PERCENTIL_GRUPO_PAR
0,"2,MINISTERIO DE RELACIONES EXTERIORES,MINISTER...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"4,MINISTERIO DE HACIENDA Y CRÉDITO PÚBLICO,MIN...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"5,MINISTERIO DE DEFENSA NACIONAL,MINISTERIO,NA...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"6,MINISTERIO DE AGRICULTURA Y DESARROLLO RURAL...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"9,MINISTERIO DE MINAS Y ENERGÍA,MINISTERIO,NAC...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
468596,9889,INSTITUTO MUNICIPAL PARA EL DEPORTE Y LA RECRE...,NO APLICA,TERRITORIAL,NO APLICA,5031.0,AMALFI,19.0,POL12,Participación Ciudadana en la Gestión Pública,4865.0,2021.0,4.505532e+09,8.499833e+09,1.478000e+03,3.0,56.0
468597,9889,INSTITUTO MUNICIPAL PARA EL DEPORTE Y LA RECRE...,NO APLICA,TERRITORIAL,NO APLICA,5031.0,AMALFI,19.0,POL13,Seguimiento y Evaluación del Desempeño Institu...,577903.0,2021.0,4.972473e+09,9.671638e+08,1.372550e+05,4.0,75.0
468598,9889,INSTITUTO MUNICIPAL PARA EL DEPORTE Y LA RECRE...,NO APLICA,TERRITORIAL,NO APLICA,5031.0,AMALFI,19.0,POL14,Gestión Documental,513531.0,2021.0,4.443824e+09,9.821682e+09,1.000000e+01,4.0,70.0
468599,9889,INSTITUTO MUNICIPAL PARA EL DEPORTE Y LA RECRE...,NO APLICA,TERRITORIAL,NO APLICA,5031.0,AMALFI,19.0,POL15,Gestión del Conocimiento,515971.0,2021.0,5.313749e+09,9.839760e+09,1.235453e+09,3.0,57.0
468600,9889,INSTITUTO MUNICIPAL PARA EL DEPORTE Y LA RECRE...,NO APLICA,TERRITORIAL,NO APLICA,5031.0,AMALFI,19.0,POL16,Control Interno,513134.0,2021.0,4.535415e+06,8.771527e+09,1.000000e+01,4.0,73.0

In [5]:
Tdesempeno.head(2)

,CODIGO_SIGEP,ENTIDAD,NATURALEZA_JURIDICA,ORDEN,SECTOR,ID_MUNICIPIO,MUNICIPIO,GRUPOPAR,ID_INDICE,INDICE,PUNTAJE_ENTIDAD,VIGENCIA,PROMEDIO_GRUPO_PAR,MAXIMO_GRUPO_PAR,MINIMO_GRUPO_PAR,QUINTIL_GRUPO_PAR,PERCENTIL_GRUPO_PAR
0,"2,MINISTERIO DE RELACIONES EXTERIORES,MINISTER...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"4,MINISTERIO DE HACIENDA Y CRÉDITO PÚBLICO,MIN...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
Tdesempeno.info()
Tdesempeno.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 468601 entries, 0 to 468600
Data columns (total 17 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   CODIGO_SIGEP         468601 non-null  object
 1   ENTIDAD              413805 non-null  object
 2   NATURALEZA_JURIDICA  413668 non-null  object
 3   ORDEN                413805 non-null  object
 4   SECTOR               413805 non-null  object
 5   ID_MUNICIPIO         413805 non-null  float64
 6   MUNICIPIO            413575 non-null  object
 7   GRUPOPAR             413805 non-null  float64
 8   ID_INDICE            413805 non-null  object
 9   INDICE               413805 non-null  object
 10  PUNTAJE_ENTIDAD      413805 non-null  float64
 11  VIGENCIA             413805 non-null  float64
 12  PROMEDIO_GRUPO_PAR   413805 non-null  float64
 13  MAXIMO_GRUPO_PAR     413805 non-null  float64
 14  MINIMO_GRUPO_PAR     413805 non-null  float64
 15  QUINTIL_GRUPO_PAR    413805 non-null  float64
 16  PERCENTIL_GRUPO_PAR  413805 non-null  float64
dtypes: float64(9), object(8)
memory usage: 60.8+ MB

CODIGO_SIGEP            object
ENTIDAD                 object
NATURALEZA_JURIDICA     object
ORDEN                   object
SECTOR                  object
ID_MUNICIPIO           float64
MUNICIPIO               object
GRUPOPAR               float64
ID_INDICE               object
INDICE                  object
PUNTAJE_ENTIDAD        float64
VIGENCIA               float64
PROMEDIO_GRUPO_PAR     float64
MAXIMO_GRUPO_PAR       float64
MINIMO_GRUPO_PAR       float64
QUINTIL_GRUPO_PAR      float64
PERCENTIL_GRUPO_PAR    float64
dtype: object

In [9]:
Tdesempeno.shape

(468601, 17)

In [10]:
Tdesempeno.index

RangeIndex(start=0, stop=468601, step=1)

In [16]:
Tdesempeno["SECTOR"].unique()
Tdesempeno["SECTOR"].value_counts()

SECTOR
NO APLICA                                             397761
AMBIENTE Y DESARROLLO SOSTENIBLE                        2800
EDUCACIÓN                                               2467
HACIENDA Y CRÉDITO PÚBLICO                              2448
DEFENSA                                                 1485
SALUD Y PROTECCIÓN SOCIAL                                953
MINAS Y ENERGÍA                                          726
TECNOLOGÍAS DE LA INFORMACIÓN Y LAS COMUNICACIONES       694
INTERIOR                                                 590
TRABAJO                                                  541
TRANSPORTE                                               539
PRESIDENCIA DE LA REPÚBLICA                              533
JUSTICIA Y DEL DERECHO                                   489
CULTURA                                                  360
INCLUSIÓN SOCIAL Y RECONCILIACIÓN                        357
PLANEACIÓN                                               263
RELACIONES EXTERIORES                                    180
VIVIENDA CIUDAD Y TERRITORIO                             180
FUNCIÓN PÚBLICA                                          179
ESTADÍSTICAS                                             179
INTELIGENCIA ESTRATÉGICA Y CONTRAINTELIGENCIA             81
Name: count, dtype: int64

In [17]:
Columnas=["SECTOR","PUNTAJE_ENTIDAD"]
Tdesempeno[Columnas]

           SECTOR  PUNTAJE_ENTIDAD
0             NaN              NaN
1             NaN              NaN
2             NaN              NaN
3             NaN              NaN
4             NaN              NaN
...           ...              ...
468596  NO APLICA           4865.0
468597  NO APLICA         577903.0
468598  NO APLICA         513531.0
468599  NO APLICA         515971.0
468600  NO APLICA         513134.0

[468601 rows x 2 columns]